In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import GridSearchCV
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import  KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier

In [2]:
dataset_train = pd.read_csv('fraudTrain.csv')
dataset_train.head(3)

Unnamed: 0 trans_date_trans_time            cc_num  \
0           0   2019-01-01 00:00:18  2703186189652095   
1           1   2019-01-01 00:00:44      630423337322   
2           2   2019-01-01 00:00:51    38859492057661   

                          merchant       category     amt      first     last  \
0       fraud_Rippin, Kub and Mann       misc_net    4.97   Jennifer    Banks   
1  fraud_Heller, Gutmann and Zieme    grocery_pos  107.23  Stephanie     Gill   
2             fraud_Lind-Buckridge  entertainment  220.11     Edward  Sanchez   

  gender                        street  ...      lat      long  city_pop  \
0      F                561 Perry Cove  ...  36.0788  -81.1781      3495   
1      F  43039 Riley Greens Suite 393  ...  48.8878 -118.2105       149   
2      M      594 White Dale Suite 530  ...  42.1808 -112.2620      4154   

                                 job         dob  \
0          Psychologist, counselling  1988-03-09   
1  Special educational needs teacher  1978-06-21   
2        Nature conservation officer  1962-01-19   

                          trans_num   unix_time  merch_lat  merch_long  \
0  0b242abb623afc578575680df30655b9  1325376018  36.011293  -82.048315   
1  1f76529f8574734946361c461b024d99  1325376044  49.159047 -118.186462   
2  a1a22d70485983eac12b5b88dad1cf95  1325376051  43.150704 -112.154481   

   is_fraud  
0         0  
1         0  
2         0  

[3 rows x 23 columns]

In [4]:
dataset_test = pd.read_csv('fraudTest.csv')


***Pre-Processing***

In [ ]:
dataset_train.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [ ]:
dataset_train.drop(columns=["Unnamed: 0", "dob", "trans_num", "street"], inplace= True)
dataset_train.head(3)

trans_date_trans_time            cc_num                         merchant  \
0   2019-01-01 00:00:18  2703186189652095       fraud_Rippin, Kub and Mann   
1   2019-01-01 00:00:44      630423337322  fraud_Heller, Gutmann and Zieme   
2   2019-01-01 00:00:51    38859492057661             fraud_Lind-Buckridge   

        category     amt      first     last gender            city state  \
0       misc_net    4.97   Jennifer    Banks      F  Moravian Falls    NC   
1    grocery_pos  107.23  Stephanie     Gill      F          Orient    WA   
2  entertainment  220.11     Edward  Sanchez      M      Malad City    ID   

     zip      lat      long  city_pop                                job  \
0  28654  36.0788  -81.1781      3495          Psychologist, counselling   
1  99160  48.8878 -118.2105       149  Special educational needs teacher   
2  83252  42.1808 -112.2620      4154        Nature conservation officer   

    unix_time  merch_lat  merch_long  is_fraud  
0  1325376018  36.011293  -82.048315         0  
1  1325376044  49.159047 -118.186462         0  
2  1325376051  43.150704 -112.154481         0

In [ ]:
data = dataset_train.head(30000)
data.is_fraud.value_counts()

is_fraud
0    29712
1      288
Name: count, dtype: int64

In [ ]:
dataset_train_processed = pd.get_dummies(data=data, sparse= True)
dataset_train_processed

cc_num     amt    zip      lat      long  city_pop  \
0      2703186189652095    4.97  28654  36.0788  -81.1781      3495   
1          630423337322  107.23  99160  48.8878 -118.2105       149   
2        38859492057661  220.11  83252  42.1808 -112.2620      4154   
3      3534093764340240   45.00  59632  46.2306 -112.1138      1939   
4       375534208663984   41.96  24433  38.4207  -79.4629        99   
...                 ...     ...    ...      ...       ...       ...   
29995  3525590521269779    4.80  27258  36.0424  -79.3242      6006   
29996   376445266762684    2.01  69165  41.1558 -101.1360      1789   
29997      630424987505   36.52  26292  39.1505  -79.5030       836   
29998  3567527758368741  118.50  76951  31.8351 -101.0017      1143   
29999  3599237318576484  175.90  42731  36.8421  -85.5396       341   

        unix_time  merch_lat  merch_long  is_fraud  ...  job_Video editor  \
0      1325376018  36.011293  -82.048315         0  ...             False   
1      1325376044  49.159047 -118.186462         0  ...             False   
2      1325376051  43.150704 -112.154481         0  ...             False   
3      1325376076  47.034331 -112.561071         0  ...             False   
4      1325376186  38.674999  -78.632459         0  ...             False   
...           ...        ...         ...       ...  ...               ...   
29995  1326915862  36.440097  -79.589525         0  ...             False   
29996  1326915881  40.312965 -101.664355         0  ...             False   
29997  1326915972  39.313899  -80.038231         0  ...             False   
29998  1326916227  31.497897 -101.595871         0  ...             False   
29999  1326916316  36.860356  -84.601402         0  ...             False   

       job_Visual merchandiser  job_Volunteer coordinator  job_Warden/ranger  \
0                        False                      False              False   
1                        False                      False              False   
2                        False                      False              False   
3                        False                      False              False   
4                        False                      False              False   
...                        ...                        ...                ...   
29995                    False                      False              False   
29996                    False                      False              False   
29997                    False                      False              False   
29998                    False                      False              False   
29999                    False                      False              False   

       job_Waste management officer  job_Water engineer  \
0                             False               False   
1                             False               False   
2                             False               False   
3                             False               False   
4                             False               False   
...                             ...                 ...   
29995                         False               False   
29996                         False               False   
29997                         False               False   
29998                         False               False   
29999                         False               False   

       job_Water quality scientist  job_Web designer  job_Wellsite geologist  \
0                            False             False                   False   
1                            False             False                   False   
2                            False             False                   False   
3                            False             False                   False   
4                            False             False                   False   
...                            ...               ...                     ...   
29995    

In [ ]:
x_train=dataset_train_processed.drop(columns='is_fraud', axis = 1)
y_train=dataset_train_processed['is_fraud']

In [ ]:
dataset_test.drop(columns=["Unnamed: 0", "dob", "trans_num", "street"], inplace= True)
dataset_test.head(3)

trans_date_trans_time            cc_num  \
0   2020-06-21 12:14:25  2291163933867244   
1   2020-06-21 12:14:33  3573030041201292   
2   2020-06-21 12:14:53  3598215285024754   

                               merchant        category    amt   first  \
0                 fraud_Kirlin and Sons   personal_care   2.86    Jeff   
1                  fraud_Sporer-Keebler   personal_care  29.84  Joanne   
2  fraud_Swaniawski, Nitzsche and Welch  health_fitness  41.28  Ashley   

       last gender      city state    zip      lat      long  city_pop  \
0   Elliott      M  Columbia    SC  29209  33.9659  -80.9355    333497   
1  Williams      F   Altonah    UT  84002  40.3207 -110.4360       302   
2     Lopez      F  Bellmore    NY  11710  40.6729  -73.5365     34496   

                      job   unix_time  merch_lat  merch_long  is_fraud  
0     Mechanical engineer  1371816865  33.986391  -81.200714         0  
1  Sales professional, IT  1371816873  39.450498 -109.960431         0  
2       Librarian, public  1371816893  40.495810  -74.196111         0

In [ ]:
data_test = dataset_train.head(30000)
data_test.is_fraud.value_counts()

is_fraud
0    29712
1      288
Name: count, dtype: int64

In [ ]:
dataset_test_processed = pd.get_dummies(data=data_test, sparse= True)
dataset_test_processed

cc_num     amt    zip      lat      long  city_pop  \
0      2703186189652095    4.97  28654  36.0788  -81.1781      3495   
1          630423337322  107.23  99160  48.8878 -118.2105       149   
2        38859492057661  220.11  83252  42.1808 -112.2620      4154   
3      3534093764340240   45.00  59632  46.2306 -112.1138      1939   
4       375534208663984   41.96  24433  38.4207  -79.4629        99   
...                 ...     ...    ...      ...       ...       ...   
29995  3525590521269779    4.80  27258  36.0424  -79.3242      6006   
29996   376445266762684    2.01  69165  41.1558 -101.1360      1789   
29997      630424987505   36.52  26292  39.1505  -79.5030       836   
29998  3567527758368741  118.50  76951  31.8351 -101.0017      1143   
29999  3599237318576484  175.90  42731  36.8421  -85.5396       341   

        unix_time  merch_lat  merch_long  is_fraud  ...  job_Video editor  \
0      1325376018  36.011293  -82.048315         0  ...             False   
1      1325376044  49.159047 -118.186462         0  ...             False   
2      1325376051  43.150704 -112.154481         0  ...             False   
3      1325376076  47.034331 -112.561071         0  ...             False   
4      1325376186  38.674999  -78.632459         0  ...             False   
...           ...        ...         ...       ...  ...               ...   
29995  1326915862  36.440097  -79.589525         0  ...             False   
29996  1326915881  40.312965 -101.664355         0  ...             False   
29997  1326915972  39.313899  -80.038231         0  ...             False   
29998  1326916227  31.497897 -101.595871         0  ...             False   
29999  1326916316  36.860356  -84.601402         0  ...             False   

       job_Visual merchandiser  job_Volunteer coordinator  job_Warden/ranger  \
0                        False                      False              False   
1                        False                      False              False   
2                        False                      False              False   
3                        False                      False              False   
4                        False                      False              False   
...                        ...                        ...                ...   
29995                    False                      False              False   
29996                    False                      False              False   
29997                    False                      False              False   
29998                    False                      False              False   
29999                    False                      False              False   

       job_Waste management officer  job_Water engineer  \
0                             False               False   
1                             False               False   
2                             False               False   
3                             False               False   
4                             False               False   
...                             ...                 ...   
29995                         False               False   
29996                         False               False   
29997                         False               False   
29998                         False               False   
29999                         False               False   

       job_Water quality scientist  job_Web designer  job_Wellsite geologist  \
0                            False             False                   False   
1                            False             False                   False   
2                            False             False                   False   
3                            False             False                   False   
4                            False             False                   False   
...                            ...               ...                     ...   
29995    

In [ ]:
x_test=dataset_test_processed.drop(columns='is_fraud', axis = 1)
y_test=dataset_test_processed['is_fraud']

**Logistic Regression**

In [ ]:
classifier = LogisticRegression(solver= 'liblinear', random_state= 0)
classifier.fit(x_train, y_train)

c:\Users\prath\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:869: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(


LogisticRegression(random_state=0, solver='liblinear')

In [ ]:
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
ac = accuracy_score(y_test, y_pred)
print(ac)

c:\Users\prath\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:869: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(


[[29712     0]
 [  288     0]]
0.9904


**Decision Tree**

In [ ]:
classifier = DecisionTreeClassifier(criterion= 'entropy', random_state= 37)
classifier.fit(x_train, y_train)

c:\Users\prath\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:869: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(


DecisionTreeClassifier(criterion='entropy', random_state=37)

In [ ]:
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
ac = accuracy_score(y_test, y_pred)
print(ac)

c:\Users\prath\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:869: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(


[[29712     0]
 [    0   288]]
1.0


**Random Forest**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators= 10,criterion= 'entropy', random_state= 37)
classifier.fit(x_train, y_train)

c:\Users\prath\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:869: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(


RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=37)

In [ ]:
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
ac = accuracy_score(y_test, y_pred)
print(ac)

c:\Users\prath\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:869: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(


[[29712     0]
 [   11   277]]
0.9996333333333334


**XG BOOST**

In [ ]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(x_train, y_train)

c:\Users\prath\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:508: FutureWarning: Allowing arbitrary scalar fill_value in SparseDtype is deprecated. In a future version, the fill_value must be a valid value for the SparseDtype.subtype.
  arr: np.ndarray = transformed.values


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [ ]:
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

c:\Users\prath\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:508: FutureWarning: Allowing arbitrary scalar fill_value in SparseDtype is deprecated. In a future version, the fill_value must be a valid value for the SparseDtype.subtype.
  arr: np.ndarray = transformed.values


[[29712     0]
 [    0   288]]


1.0